add interrupt message

diff --git a/rftp b/rftp
--- a/rftp
+++ b/rftp
@@ -2,14 +2,14 @@
 
 
 #Check prerequisites
-command -v lftp >/dev/null 2>&1 || { echo >&2 "I require lftp but it's not installed.  Aborting."; exit 1; }
-command -v lockfile >/dev/null 2>&1 || { echo >&2 "I require lockfile but it's not installed.  Aborting."; exit 1; }
+command -v lftp >/dev/null 2>&1 || { echo >&2 "I require lftp but it's not installed.  Aborting.\n"; exit 1; }
+command -v lockfile >/dev/null 2>&1 || { echo >&2 "I require lockfile but it's not installed.  Aborting.\n"; exit 1; }
 
 
 #Load config files
 CONFIG="$HOME/.rftp.conf"
 if [ ! -r $CONFIG ]; then
-  echo "Config file $CONFIG is missing!"
+  echo "Config file $CONFIG is missing!\n"
   exit 1
 fi
 source $CONFIG
@@ -20,7 +20,7 @@ LOCKFILE="/tmp/rftp.lock"
 lockfile -r 0 $LOCKFILE 2>/dev/null || exit 0
 
 #Remove lockfile if lftp terminates unexpected
-trap "echo 'ERROR: lftp interrupted'; rm -f $LOCKFILE; exit" SIGINT SIGTERM
+trap "echo 'ERROR: lftp interrupted\n'; rm -f $LOCKFILE; exit 1" SIGINT SIGTERM
 
 lftp -u $login,$pass -p $port sftp://$host << EOF
 set mirror:use-pget-n 5
